<template>

    <Drawer direction="bottom">

        <DrawerTrigger as-child>
            <Button variant="outline">
                Open Drawer
            </Button>
        </DrawerTrigger>

        <DrawerContent>

            <div class="mx-auto w-full max-w-xl py-10">

                <DrawerHeader>

                    <DrawerTitle>Generate your own story</DrawerTitle>

                    <DrawerDescription>Write down what your story should be about</DrawerDescription>

                </DrawerHeader>

                <DrawerFooter>

                    <div class="grid w-full gap-2">
                        <Textarea placeholder="Write a funny story about how the dinosaur turned into chickens..."/>
                        <Button>Generate!</Button>
                    </div>

                </DrawerFooter>

            </div>

        </DrawerContent>

    </Drawer>

    <Drawer @update:open="drawer.shouldOpen = $event" :modal="false" :open="drawer.shouldOpen" direction="bottom"
            :dismissible="true">

        <DrawerContent>
            <Book :book="drawer.book"/>
        </DrawerContent>

    </Drawer>

    <div class="flex flex-col justify-center items-center space-y-20 text-black">

        <img src="./assets/girl.png" alt="">

        <div class="w-full h-20 bg-[#F18533] rounded-full"/>

        <h1 class="text-6xl text-black text-center">
            Search across thousands<br>
            of books fully generated by AI
        </h1>

        <div class="space-y-8 px-8">

            <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-x-4 gap-y-8 text-center">

                <div v-for="book in books" class="w-50 lg:w-64 space-y-2 mx-auto" @click="viewBook(book)">

                    <img class="rounded-2xl" :src="book.cover" alt="">

                    <div class="text-xl">
                        {{ book.title }}
                    </div>

                </div>

            </div>

        </div>

        <div class="absolute hidden">
            <Book v-show="prerender" :key="prerender?.key" :book="prerender?.data"/>
        </div>

    </div>

</template>

<script lang="ts" setup>

    import Book, { ViewBookResponse } from './components/Book.vue'
    import { Button } from '../@/components/ui/button'
    import { Textarea } from '../@/components/ui/textarea'

    import {
        Dialog,
        DialogContent,
        DialogDescription,
        DialogFooter,
        DialogHeader,
        DialogTitle,
        DialogTrigger,
    } from '../@/components/ui/dialog'

    import {
        Drawer,
        DrawerClose,
        DrawerContent,
        DrawerDescription,
        DrawerFooter,
        DrawerHeader,
        DrawerTitle,
        DrawerTrigger,
    } from '../@/components/ui/drawer'
    import { Minus, Plus } from 'lucide-vue-next'
    import { ref } from 'vue'

    const drawer = ref({
        shouldOpen: false,
        book: null,
    })

    const prerender = ref({})

    function viewBook(book: ViewBookResponse) {

        fetch(`https://api.docker.localhost/book/${ book.id }`)
            .then(response => response.json())
            .then((response: ViewBookResponse) => {
                // console.log(drawer.value)
                // book.value = response

                drawer.value.shouldOpen = true
                drawer.value.book = response

            })

    }

    type BooksResponse = {
        data: Array<ViewBookResponse>
    }

    const books = ref<Array<ViewBookResponse>>()

    fetch('https://api.docker.localhost/books')
        .then(response => response.json())
        .then((response: BooksResponse) => {
            books.value = response.data
        })

</script>

<style>

</style>
