<template>

    <div class="flex flex-col justify-center items-center space-y-20 text-black">

        <img src="./assets/girl.png" alt="">

        <div class="w-full h-20 bg-[#F18533] rounded-full"/>

        <h1 class="text-6xl text-black text-center">
            Search across thousands<br>
            of books fully generated by AI
        </h1>

        <div class="space-y-8">

            <div class="flex space-x-4 text-center" v-for="_ in 4">

                <div v-for="_ in 4" class="w-60 space-y-2">

                    <img class="rounded-2xl " src="./assets/cover.png" alt="">

                    <div class="text-xl">
                        Max and the Magic Paintbrush
                    </div>

                </div>

            </div>

        </div>

    </div>

</template>

<script lang="ts" setup>

    import Book from './components/Book.vue'

</script>

<style>

</style>
