export const debounce = <T>(wait: number, callback: (...args: any[]) => Promise<T>) => {

    let timeoutId: undefined | number

    return (...args: any[]) => {
        window.clearTimeout(timeoutId)
        timeoutId = window.setTimeout(() => callback(...args), wait)
    }

}

export function randomSearchTerm(): string {

    const searchTerms = [
        'A talking octopus in outer space',
        'A magical forest of invisible animals',
        'The adventures of a shape-shifting snail',
        'A dragon who can’t breathe fire',
        'The lost city of jellybean fairies',
        'A time-traveling kitten’s mission',
        'The pirate penguins of Crystal Cove',
        'A dog who paints rainbows in the sky',
        'The secret treehouse of the tiny dinosaurs',
        'A hedgehog who glows in the dark',
        'The mystery of the singing seashells',
        'A turtle with a magic map on its shell',
        'The mermaid who collects stars',
        'A bear with an enchanted backpack',
        'The robot who wanted to be a real boy',
        'An owl that can change the weather',
        'The cloud castle and the bubble unicorns',
        'A fox who teaches the stars to dance',
        'The invisible bridge to candyland',
        'A mischievous fairy in a teapot',
        'The lighthouse with magical windows',
        'A squirrel who bakes invisible cookies',
        'The enchanted umbrella that flies to secret lands',
        'A garden where flowers can talk',
        'The sleepy moon that tells bedtime stories',
        'A jellyfish that glows with emotions',
        'The snail who paints the stars',
        'A giraffe who discovers a hidden world underground',
        'The enchanted snow globe that changes seasons',
        'The snail and the secret language of pebbles',
        'A panda who makes friends with shadows',
        'The treasure map hidden in the rainbow',
        'A dancing cactus in a desert carnival',
        'The friendly yeti who skates on clouds',
        'A fox that writes wishes in the sand',
        'The magical train that travels through dreams',
        'A mouse who invents time-traveling cheese',
        'The golden butterfly and the hidden valley',
        'A koala who knows all the animal secrets',
        'The enchanted lake where fish tell stories',
        'The lighthouse with magical windows',
        'A squirrel who bakes invisible cookies',
        'The enchanted umbrella that flies to secret lands',
        'A garden where flowers can talk',
        'The sleepy moon that tells bedtime stories',
        'A jellyfish that glows with emotions',
        'The snail who paints the stars',
        'A giraffe who discovers a hidden world underground',
        'The enchanted snow globe that changes seasons',
        'The snail and the secret language of pebbles',
        'A panda who makes friends with shadows',
        'The treasure map hidden in the rainbow',
        'A dancing cactus in a desert carnival',
        'The friendly yeti who skates on clouds',
        'A fox that writes wishes in the sand',
        'The magical train that travels through dreams',
        'A mouse who invents time-traveling cheese',
        'The golden butterfly and the hidden valley',
        'A koala who knows all the animal secrets',
        'The enchanted lake where fish tell stories',
        'A magical panda that paints the night sky',
        'The secret world under Grandpa`s rocking chair',
        'A squirrel with a rainbow tail who grants wishes',
        'The talking telescope that sees into fairy realms',
        'A cat that bakes muffins in the clouds',
        'The tiny kingdom inside a snowflake',
        'A starfish with magical, glowing arms',
        'The unicorn who changes colors with the seasons',
        'A sleepy owl who can read people`s dreams',
        'The hidden world behind the old bookshelf',
        'A hedgehog who makes friends with shadows',
        'The wishing well that only grants silly wishes',
        'A hamster who builds floating castles',
        'The forest where trees whisper secrets',
        'A magical scarf that can change shapes',
        'The city of glowing mushrooms in the woods',
        'A butterfly that can freeze time',
        'The firefly who loves to paint the night',
        'A rabbit with a map to the land of giants',
        'The dog who chases rainbows and finds treasures',
        'The enchanted carousel that spins into other worlds',
        'A fish with a crown and a quest for courage',
        'The garden of giggling flowers',
        'A magical treehouse that travels through history',
        'The pirate parrot who guards an invisible treasure',
        'A penguin who dreams of flying',
        'The giant’s shoes that take you on adventures',
        'A giraffe who tells stories through dance',
        'The mysterious lighthouse that sings',
        'A fire-breathing turtle who becomes a hero',
        'The fairy queen with magical dust for bravery',
        'A jellyfish who can turn into any sea creature',
        'The shadow that becomes your best friend',
        'A bunny who bakes wishes into cakes',
        'The enchanted forest that glows in the dark',
        'A wolf who makes wishes under the moon',
        'The magical hot air balloon of lost toys',
        'A crab who finds hidden messages in shells',
        'The time-traveling squirrel and his acorn',
        'A lion who guards a land of dreams',
        'The mountain of golden leaves',
        'A raccoon who draws stars in the sky',
        'The dragon who lives in a teapot',
        'A hummingbird with a magical song',
        'The secret underwater library of stories',
        'The dinosaur that only comes out in winter',
        'The puppy who makes new colors in the world',
        'A dolphin who guides explorers through coral caves',
        'The fox who catches sunbeams in a jar',
        'The spider who spins webs of wishes',
        'A snail that travels at the speed of light',
        'The enchanted forest of crystal leaves',
        'A kitten who can talk to rivers',
        'The magic brush that brings drawings to life',
        'The wise old tortoise who knows all secrets',
        'A snow leopard who guards the Crystal Valley',
        'The owl who keeps the library of forgotten books',
        'The invisible wolf who teaches bravery',
        'A mermaid who rescues shooting stars',
        'The rainbow trout that hides in dreams',
        'The tiny elephant with enormous courage',
        'A wisecracking frog who invents magical potions',
        'The magical fountain that makes you laugh',
        'A chameleon who changes colors based on feelings',
        'The peacock who writes love letters to the sun',
        'A bear who collects glowing rocks',
        'The river of silver fish that grant wishes',
        'A fox who carries secrets in its fur',
        'The ship that sails through moonlight',
        'A golden bunny who brings springtime',
        'The forgotten castle at the end of the rainbow',
        'The snail who knits blankets for other animals',
        'A friendly robot that travels through time',
        'The valley of talking windmills',
        'The dolphin who sings the moon to sleep',
        'A tiger who guards the last enchanted tree',
        'The story of the flying cheese and mouse explorer',
        'A llama with a map of hidden worlds',
        'The glimmering bridge to the land of dreams',
        'A magical suitcase that brings toys to life',
        'The enchanted forest with candy trees',
        'A mouse who builds little inventions for friends',
        'The river otter who hides golden secrets',
        'The talking seashell that tells ancient stories',
        'The invisible squirrel with the heart of a lion',
        'The lantern that lights up hidden islands',
        'A dragonfly who paints pictures in the clouds',
        'The enchanted book that reads itself to children',
        'A bear who teaches dance to butterflies',
        'The land of glowing crystals under the ocean',
        'The talking lion statue in the magical garden',
        'A turtle who makes friends with a moonbeam',
        'The garden with flowers that tell jokes',
        'The bird who leaves glowing feathers at dawn',
        'The playful panda who controls the seasons',
        'The fox who teaches clouds to dance',
        'A rabbit with a pocket watch for time travel',
        'The elephant who paints the night sky',
        'The cloud village where stars go to rest',
        'A zebra who runs faster than the wind',
    ]

    const randomIndex = Math.floor(Math.random() * searchTerms.length)

    return `${ searchTerms[ randomIndex ] }...`

}