export const debounce = <T>(wait: number, callback: (...args: any[]) => Promise<T>) => {

    let timeoutId: undefined | number

    return (...args: any[]) => {
        window.clearTimeout(timeoutId)
        timeoutId = window.setTimeout(() => callback(...args), wait)
    }

}

export function randomSearchTerm(): string {

    const searchTerms = [
        'A talking octopus in outer space',
        'A magical forest of invisible animals',
        'The adventures of a shape-shifting snail',
        'A dragon who can’t breathe fire',
        'The lost city of jellybean fairies',
        'A time-traveling kitten’s mission',
        'The pirate penguins of Crystal Cove',
        'A dog who paints rainbows in the sky',
        'The secret treehouse of the tiny dinosaurs',
        'A hedgehog who glows in the dark',
        'The mystery of the singing seashells',
        'A turtle with a magic map on its shell',
        'The mermaid who collects stars',
        'A bear with an enchanted backpack',
        'The robot who wanted to be a real boy',
        'An owl that can change the weather',
        'The cloud castle and the bubble unicorns',
        'A fox who teaches the stars to dance',
        'The invisible bridge to candyland',
        'A mischievous fairy in a teapot',
        'The lighthouse with magical windows',
        'A squirrel who bakes invisible cookies',
        'The enchanted umbrella that flies to secret lands',
        'A garden where flowers can talk',
        'The sleepy moon that tells bedtime stories',
        'A jellyfish that glows with emotions',
        'The snail who paints the stars',
        'A giraffe who discovers a hidden world underground',
        'The enchanted snow globe that changes seasons',
        'The snail and the secret language of pebbles',
        'A panda who makes friends with shadows',
        'The treasure map hidden in the rainbow',
        'A dancing cactus in a desert carnival',
        'The friendly yeti who skates on clouds',
        'A fox that writes wishes in the sand',
        'The magical train that travels through dreams',
        'A mouse who invents time-traveling cheese',
        'The golden butterfly and the hidden valley',
        'A koala who knows all the animal secrets',
        'The enchanted lake where fish tell stories',
        'The lighthouse with magical windows',
        'A squirrel who bakes invisible cookies',
        'The enchanted umbrella that flies to secret lands',
        'A garden where flowers can talk',
        'The sleepy moon that tells bedtime stories',
        'A jellyfish that glows with emotions',
        'The snail who paints the stars',
        'A giraffe who discovers a hidden world underground',
        'The enchanted snow globe that changes seasons',
        'The snail and the secret language of pebbles',
        'A panda who makes friends with shadows',
        'The treasure map hidden in the rainbow',
        'A dancing cactus in a desert carnival',
        'The friendly yeti who skates on clouds',
        'A fox that writes wishes in the sand',
        'The magical train that travels through dreams',
        'A mouse who invents time-traveling cheese',
        'The golden butterfly and the hidden valley',
        'A koala who knows all the animal secrets',
        'The enchanted lake where fish tell stories',
        'A magical panda that paints the night sky',
        'The secret world under Grandpa`s rocking chair',
        'A squirrel with a rainbow tail who grants wishes',
        'The talking telescope that sees into fairy realms',
        'A cat that bakes muffins in the clouds',
        'The tiny kingdom inside a snowflake',
        'A starfish with magical, glowing arms',
        'The unicorn who changes colors with the seasons',
        'A sleepy owl who can read people`s dreams',
        'The hidden world behind the old bookshelf',
        'A hedgehog who makes friends with shadows',
        'The wishing well that only grants silly wishes',
        'A hamster who builds floating castles',
        'The forest where trees whisper secrets',
        'A magical scarf that can change shapes',
        'The city of glowing mushrooms in the woods',
        'A butterfly that can freeze time',
        'The firefly who loves to paint the night',
        'A rabbit with a map to the land of giants',
        'The dog who chases rainbows and finds treasures',
        'The enchanted carousel that spins into other worlds',
        'A fish with a crown and a quest for courage',
        'The garden of giggling flowers',
        'A magical treehouse that travels through history',
        'The pirate parrot who guards an invisible treasure',
        'A penguin who dreams of flying',
        'The giant’s shoes that take you on adventures',
        'A giraffe who tells stories through dance',
        'The mysterious lighthouse that sings',
        'A fire-breathing turtle who becomes a hero',
        'The fairy queen with magical dust for bravery',
        'A jellyfish who can turn into any sea creature',
        'The shadow that becomes your best friend',
        'A bunny who bakes wishes into cakes',
        'The enchanted forest that glows in the dark',
        'A wolf who makes wishes under the moon',
        'The magical hot air balloon of lost toys',
        'A crab who finds hidden messages in shells',
        'The time-traveling squirrel and his acorn',
        'A lion who guards a land of dreams',
        'The mountain of golden leaves',
        'A raccoon who draws stars in the sky',
        'The dragon who lives in a teapot',
        'A hummingbird with a magical song',
        'The secret underwater library of stories',
        'The dinosaur that only comes out in winter',
        'The puppy who makes new colors in the world',
        'A dolphin who guides explorers through coral caves',
        'The fox who catches sunbeams in a jar',
        'The spider who spins webs of wishes',
        'A snail that travels at the speed of light',
        'The enchanted forest of crystal leaves',
        'A kitten who can talk to rivers',
        'The magic brush that brings drawings to life',
        'The wise old tortoise who knows all secrets',
        'A snow leopard who guards the Crystal Valley',
        'The owl who keeps the library of forgotten books',
        'The invisible wolf who teaches bravery',
        'A mermaid who rescues shooting stars',
        'The rainbow trout that hides in dreams',
        'The tiny elephant with enormous courage',
        'A wisecracking frog who invents magical potions',
        'The magical fountain that makes you laugh',
        'A chameleon who changes colors based on feelings',
        'The peacock who writes love letters to the sun',
        'A bear who collects glowing rocks',
        'The river of silver fish that grant wishes',
        'A fox who carries secrets in its fur',
        'The ship that sails through moonlight',
        'A golden bunny who brings springtime',
        'The forgotten castle at the end of the rainbow',
        'The snail who knits blankets for other animals',
        'A friendly robot that travels through time',
        'The valley of talking windmills',
        'The dolphin who sings the moon to sleep',
        'A tiger who guards the last enchanted tree',
        'The story of the flying cheese and mouse explorer',
        'A llama with a map of hidden worlds',
        'The glimmering bridge to the land of dreams',
        'A magical suitcase that brings toys to life',
        'The enchanted forest with candy trees',
        'A mouse who builds little inventions for friends',
        'The river otter who hides golden secrets',
        'The talking seashell that tells ancient stories',
        'The invisible squirrel with the heart of a lion',
        'The lantern that lights up hidden islands',
        'A dragonfly who paints pictures in the clouds',
        'The enchanted book that reads itself to children',
        'A bear who teaches dance to butterflies',
        'The land of glowing crystals under the ocean',
        'The talking lion statue in the magical garden',
        'A turtle who makes friends with a moonbeam',
        'The garden with flowers that tell jokes',
        'The bird who leaves glowing feathers at dawn',
        'The playful panda who controls the seasons',
        'The fox who teaches clouds to dance',
        'A rabbit with a pocket watch for time travel',
        'The elephant who paints the night sky',
        'The cloud village where stars go to rest',
        'A zebra who runs faster than the wind',
        'A tea party inside a magical seashell palace',
        'A firefly who lights up hidden forests',
        'A turtle who joins a pirate adventure at sea',
        'A penguin who learns to dance with ice crystals',
        'A baby dragon that paints rainbows in the sky',
        'A bird that lives on a cloud and makes it rain candy',
        'A polar bear who sings the northern lights into being',
        'A koala who grows candy on trees and shares it with friends',
        'A little fox that discovers a golden feather with powers',
        'A secret library hidden at the bottom of a lake',
        'A skunk who turns shadows into magical stories',
        'A parrot who dreams of flying high enough to reach the sun',
        'A coyote that can hear the secrets of the whispering wind',
        'A firefly who paints songs in the night sky',
        'A mermaid with a rainbow in her hair who collects lost stars',
        'A rabbit who rides sunbeams across the forest',
        'A polar bear who guards icy dreams in the winter',
        'A squirrel who speaks to the stars and learns their stories',
        'A frog who jumps from cloud to cloud',
        'A crystal river filled with glowing fish',
        'A magic key that opens hearts and secret doors',
        'A deer who guards the first flowers of spring',
        'A pufferfish that makes wishes with bubbles',
        'A fairy with wings that change colors with her mood',
        'A firefly that can freeze time with a flash',
        'A crocodile with a secret lullaby that calms storms',
        'A magic box that holds endless adventures inside',
        'A fox who sees through rainbows to another world',
        'A sunflower that comes to life and walks at night',
        'A miniature world in a bottle that changes each time you look',
        'A seagull who speaks in riddles that lead to hidden treasures',
        'A pinecone that glows under moonlight',
        'A deer with wings who touches the stars at night',
        'A honeybee who paints with golden light',
        'A secret path hidden in a ladybug’s garden',
        'A wizard owl who keeps a magical book of spells',
        'A tiger who stumbles upon a hidden paradise',
        'A moth who helps the moon glow brighter',
        'A snow leopard that lives inside a sparkling jewel box',
        'A hummingbird who paints the sky at sunrise',
        'A tiny fairy who lives inside a dandelion',
        'A starfish that knows the deepest secrets of the ocean',
        'An enchanted meadow filled with dreaming stones',
        'A crow who brings winter magic to the forest',
        'A snail with a map to hidden universes',
        'A singing bridge hidden in the whispering woods',
        'A dolphin that dances with mermaids beneath the sea',
        'A flamingo who knows the songs of fairies',
        'A snow fox with golden antlers that sparkle',
        'A magical marsh where stars come to float',
        'A fairy with wings made of morning dew',
        'An owl who sees memories hidden in raindrops',
        'A secret garden where wishes grow on trees',
        'A golden toad who knows the way to magic rivers',
        'A nightingale who plays with beams of sunlight',
        'A little spider who draws dreams on its webs',
        'A butterfly that lives inside a book of fairytales',
        'A hedgehog who grows flowers that tell stories',
        'A star-catcher with a net that glows in the moonlight',
        'A chinchilla who can speak with shadows',
        'A wolf that can summon snowflakes with a howl',
        'A little bear who lives on a shooting star',
        'A forest of singing blossoms where fairies dance',
        'A gecko who paints patterns on fallen leaves',
        'A swirling tunnel made of stardust',
        'An elephant who keeps rainbow secrets in her trunk',
        'A lion who wears a crown made of stars',
        'A hidden song in the mountain that echoes with magic',
        'A tiny fox with a heart full of bravery',
        'A feather that floats through dreams',
        'A wise old owl who knows every story ever told',
        'A flower that sings at dawn and grants wishes',
        'A raccoon who finds laughter lost in the forest',
        'A tortoise who listens to the song of the river',
        'A tiger who guards a door to the dream world',
        'A penguin who walks through shadows on adventures',
        'A lion who knows the secrets of the moon',
        'A magical feather that whispers dreams to children',
        'A treehouse where fairies float and play',
        'A secret room hidden behind a rainbow door',
        'A frog who knows the names of all the stars',
        'Snow-capped hills where dreaming bears live',
        'A rabbit who finds the sunset hidden in a cloud',
        'A parrot who guards a hidden treasure map',
        'A starlit cavern filled with whispering fish',
        'A raccoon who finds lost rainbows in the sky',
        'A dolphin who jumps between worlds',
        'A cat who sleeps in a dream-catcher hammock',
        'A forest where wishes grow on every tree',
        'A shining snowflake that sings its own song',
        'An elephant who hides dreams inside bubbles',
        'A crystal leaf from the glowing forest',
        'A little bunny who lights up the night sky',
        'A butterfly with wings made of sparkling stars',
        'A bear who dreams of the ocean and the waves',
        'A mouse who travels between worlds on a magic train',
        'An enchanted lake filled with shimmering lights',
        'A squirrel who finds rainbows hidden in the clouds',
        'A secret land where humming stones sing',
        'A hedgehog who knows the way to every wish',
        'Secret island where dreams become real',
        'Unicorn who changes colors under the moonlight',
        'Rainbow bridge that leads to hidden lands',
        'Wise old turtle who knows every tree’s story',
        'Mushroom forest where laughter echoes',
        'Butterfly with wings that shimmer like gemstones',
        'Magic fountain that gives wisdom to those who drink',
        'Tiny village inside a dewdrop',
        'Dancing otters who play with golden leaves',
        'Gentle bear who listens to the whispers of the wind',
        'Fox with a secret journal of the forest’s magic',
        'Enchanted harp that plays songs of the stars',
        'Baby dragon who explores sparkling caves',
        'Talking river that tells stories of long ago',
        'Fish with glowing scales that guides lost sailors',
        'Invisible path that appears only under starlight',
        'Midnight library guarded by tiny owls',
        'Gigantic sunflower that grows dreams',
        'Crystal pond where fairies hold midnight dances',
        'Kitten who can talk to flower spirits',
        'Tree that grows candy in a secret forest',
        'Lost temple hidden in a field of flowers',
        'Sunflower field where each flower holds a wish',
        'Little squirrel with a magical acorn',
        'Golden bridge that only appears after rain',
        'Firefly lantern that shows hidden paths',
        'Ancient tree that grows sparkling gems',
        'Fox who paints the night sky with stars',
        'Singing waterfall that only appears on certain nights',
        'Lonely snowflake that wants to see the world',
        'Cloud palace that floats over the mountains',
        'Little house hidden inside a giant pumpkin',
        'Magical meadow where dreams sprout like flowers',
        'Firebird that lights up the forest at night',
        'Riverbank where moonbeams come to rest',
        'Sleeping lion who dreams of magical places',
        'Hidden valley filled with laughter and magic',
        'Waterfall that sings lullabies at night',
        'Talking pebble with stories of distant lands',
        'Magical teapot that pours stories instead of tea',
        'Forest where fireflies guide nighttime travelers',
        'Little dragon who collects forgotten wishes',
        'Path of stars that leads to hidden worlds',
        'Enchanted forest filled with glow-in-the-dark plants',
        'Little fox who learns to fly in his dreams',
        'Mirror pond that shows your happiest memory',
        'Dandelion that floats to secret lands',
        'Hidden cave where echoes come to life',
        'Sea turtle with a map to the lost city of pearls',
        'Talking seashell that shares stories of the ocean',
        'Snowy forest where snowflakes sing in harmony',
        'Treasure chest hidden in a rainbow',
        'Bear with a glowing nose that lights up dark places',
        'Whispering mist that hides magical creatures',
        'Garden of glowing flowers and tiny fairies',
        'Secret swing that transports you to the stars',
        'Singing butterfly who knows forest secrets',
        'Tiny castle hidden in a sunflower’s heart',
        'Caterpillar who dreams of becoming a wizard',
        'Mountain peak where dragons tell their legends',
        'Friendly cloud that follows the sun across the sky',
        'Magical forest where rain creates rainbows',
        'Snow leopard who watches over the northern lights',
        'Fountain of youth hidden inside an ancient oak',
        'Wise owl who sees the past in puddles',
        'Secret path in the forest that leads to moonbeams',
        'Little duck who finds hidden treasure underwater',
        'Giggling squirrel who finds golden acorns',
        'Field of tall grass that whispers secrets',
        'Dragonfly who paints pictures on morning dew',
        'Firefly who can grant tiny wishes',
        'Glowing river that flows only under a full moon',
        'Tiny fox that lives in a thimble house',
        'Cloud village where birds tell stories',
        'Deer who hides in the misty mountains',
        'Midnight train that travels through dreams',
        'River that carries stars to the ocean',
        'Quiet pond where dreams come to life',
        'Butterfly who changes color with each secret',
        'Pine forest where stars fall to the ground',
        'Little bear who discovers a map to the moon',
        'Sunlit garden where shadows come alive',
        'Mountain lake filled with hidden treasures',
        'Swirling mist where fairy stories begin',
        'Sparkling rainbow that leads to a hidden island',
        'Little mouse who writes stories on leaves',
        'Cat who rides a flying fish across the sky',
        'Misty glen where dreams drift on the breeze',
        'Glow-in-the-dark forest of sparkling trees',
        'Gentle giant who plants wishes in the ground',
        'Rainbow feather that brings luck to anyone it touches',
        'Firebird who lights the stars at night',
        'Mountain cabin that only appears in dreams',
        'Talking willow tree that shares ancient tales',
        'Tiny bee who finds lost dreams in the flowers',
        'Hidden lake where fairies watch the stars',
        'Field of wildflowers that grow in every color',
        'Secret tunnel under a waterfall',
        'Bright comet that grants dreams to children',
        'Seaside cave that glows with hidden lights',
    ]

    const randomIndex = Math.floor(Math.random() * searchTerms.length)

    return `${ searchTerms[ randomIndex ] }...`

}