x-local-network: &local-network
  networks:
    - local-network

x-php: &php
  healthcheck:
    disable: true
  build:
    context: docker/php
    dockerfile: php.dockerfile
    args:
      ENVIRONMENT: development
  restart: unless-stopped
  working_dir: /srv
  volumes:
    - .:/srv

x-nvidia: &nvidia
  runtime: nvidia

x-cpu: &cpu
  environment:
    - CLI_ARGS=--cpu

services:

#  worker:
#    <<: *php
#    networks:
#      - local-network
#      - traefik-network
#    labels:
#      - traefik.enable=true
#      - traefik.http.routers.queue.entryPoints=web-secure
#      - traefik.http.routers.queue.rule=Host(`$HORIZON_DOMAIN`)
#      - traefik.http.routers.queue.tls=true

  horizon:
    <<: *php
    command: php artisan queue:work --timeout=600
    networks:
      - local-network
      - traefik-network

  scheduler:
    <<: [ *php, *local-network ]
    command: supercronic /srv/docker/php/config/schedule.cron

  redis:
    <<: *local-network
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data

  ollama:
    <<: [ *nvidia, *local-network ]
    networks:
      - local-network
      - traefik-network
    image: ollama/ollama:0.5.1
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - .ollama:/root/.ollama

  comfyui:
    <<: [ *nvidia, *local-network ]
    build:
      dockerfile: comfyui.dockerfile
      context: docker/comfyui
    restart: unless-stopped
    volumes:
      - .comfy:/home/runner
    environment:
      CLI_ARGS: '--fp8_e4m3fn-unet --fp8_e4m3fn-text-enc --reserve-vram 1'
    labels:
      - traefik.enable=true
      - traefik.http.routers.comfyui.entryPoints=web-secure
      - traefik.http.routers.comfyui.rule=Host(`$COMFYUI_DOMAIN`)
      - traefik.http.routers.comfyui.tls=true

#  open-webui:
#    image: ghcr.io/open-webui/open-webui:main
#    volumes:
#      - open-webui:/app/backend/data
#    depends_on:
#      - ollama
#    ports:
#      - "8080:8080"
#    environment:
#      - 'OLLAMA_BASE_URL=http://ollama:11434'
#      - 'WEBUI_SECRET_KEY='

volumes:
  redis-data:
  timescaledb-data:
  open-webui:

networks:
  local-network:
  traefik-network:
    name: traefik-network
    external: true
