x-local-network: &local-network
  networks:
    - local-network

x-php: &php
  healthcheck:
    disable: true
  build:
    context: docker/php
    dockerfile: php.dockerfile
    args:
      ENVIRONMENT: development
  restart: unless-stopped
  working_dir: /srv
  volumes:
    - .:/srv
    - ~/.composer:/home/composer/.composer:delegated
    - ./vendor:/srv/vendor:delegated

x-nvidia: &nvidia
  runtime: nvidia

services:

  queue:
    <<: *php
    command: php artisan queue:work --timeout=720 --tries=1 --memory=1024 --max-jobs=128
    networks:
      - local-network
      - traefik-network

  scheduler:
    <<: [ *php, *local-network ]
    command: php artisan schedule:work

  redis-worker:
    <<: *local-network
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-worker-data:/data

  comfyui:
    <<: [ *nvidia ]
    networks:
      - traefik-network
      - local-network
    build:
      dockerfile: comfyui.dockerfile
      context: docker/comfyui
    restart: unless-stopped
    volumes:
      - .comfy:/home/runner
    environment:
      CLI_ARGS: '--fp8_e4m3fn-unet --fp8_e4m3fn-text-enc --reserve-vram 1'
    labels:
      - traefik.enable=true
      - traefik.http.routers.comfyui.entryPoints=web-secure
      - traefik.http.routers.comfyui.rule=Host(`$COMFYUI_DOMAIN`)
      - traefik.http.routers.comfyui.tls=true

volumes:
  redis-worker-data:

networks:
  local-network:
  traefik-network:
    name: traefik-network
    external: true
